apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pull-request-preview
spec:
  params:
    - name: git-repo-url
      description: The git repository url
    - name: pullreq-html-url
      description: The pull request url
    - name: pullreq-sha
      description: The pr git revision
      default: master
    - name: pullreq-base-sha
      description: The base git revision
      default: master
    - name: pullreq-repo-full_name
      description: The name of the deployment to be created / patched
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: pullreq-head-ref
      description: The head branch ref
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-and-preview-$(tt.params.git-repo-name)-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: build-and-preview
        params:
          - name: git-revision
            value: $(tt.params.pullreq-sha)
          - name: git-repo-full-name
            value: $(tt.params.pullreq-repo-full_name)
          - name: git-repo-name
            value: $(tt.params.git-repo-name)
          - name: git-pr-url
            value: $(tt.params.pullreq-html-url)
          - name: git-pr-base-sha
            value: $(tt.params.pullreq-base-sha)
          - name: git-repo-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.pullreq-sha)
          - name: git-pr-head-ref
            value: $(tt.params.pullreq-head-ref)
        workspaces:
          - name: sync
            persistentVolumeClaim:
              claimName: pipeline2
            subPath: $(uid)-sync/
          - name: source
            persistentVolumeClaim:
              claimName: pipeline2
            subPath: $(uid)/
        resources:
          - name: git-repo
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(tt.params.pullreq-sha)
                - name: url
                  value: $(tt.params.git-repo-url)
                - name: depth
                  value: "0"

---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pull-request-close
spec:
  params:
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: pullreq-head-ref
      description: The head branch ref

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: undeploy-preview-$(tt.params.git-repo-name)-$(uid)
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: undeploy-preview
        params:
          - name: git-pr-head-ref
            value: $(tt.params.pullreq-head-ref)
